FROM python:3.10-slim

WORKDIR /app

# Zaroori system files install karein
RUN apt-get update && apt-get install -y wget libsndfile1 && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# NAYA Kokoro v1.0 Model aur Voices download karein
RUN wget -O kokoro-v1.0.onnx https://github.com/thewh1teagle/kokoro-onnx/releases/download/model-files-v1.0/kokoro-v1.0.onnx
RUN wget -O voices-v1.0.bin https://github.com/thewh1teagle/kokoro-onnx/releases/download/model-files-v1.0/voices-v1.0.bin

COPY handler.py .

CMD ["python", "-u", "handler.py"]